routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('foo', function () {
    return 'Hello World';
});

Route::group(['prefix'=>'admin/login','middleware'=>'CheckLogin'],function(){
    Route::get('/', 'Admin\LoginController@getLogin')->name('admin.login');
    Route::post('/', 'Admin\LoginController@postLogin')->name('admin.post.login');
});

Route::group(['prefix'=>'admin','middleware'=>'CheckAdmin'],function(){
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::resource('place', 'Admin\PlaceController');
    // Route tour
    Route::resource('tour', 'Admin\TourController');

    Route::post('/tour/update/{id}','Admin\TourController@updateTour');
    Route::get('/tour/delete/{id}','Admin\TourController@deleteTour');
    
    Route::resource('news', 'Admin\NewsController');

    // Route danh mục cha
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('banner', 'Admin\BannerController');
    Route::get('/delete/{id}','Admin\CategoryController@delete');
    // Route danh mục con
    Route::get('/child/category/{id}','Admin\CategoryController@indexCateChild')->name('catechild.index');
    Route::get('/child/category/add/{id}','Admin\CategoryController@createCateChild');
    Route::post('/child/category/add/{id}','Admin\CategoryController@storeCateChild');
    Route::get('/child/category/edit/{id}','Admin\CategoryController@showCateChild');
    Route::post('/child/category/edit/{id}','Admin\CategoryController@editCateChild');
    Route::get('/child/category/delete/{id}','Admin\CategoryController@deleteCateChild');

    //route quan ly dat hang
    Route::get('/booking', 'Admin\BookingController@getBooking')->name('book.index');
    Route::get('/booking/success', 'Admin\BookingController@getBookingSuccess')->name('book.success');
    Route::get('/booking/{id}', 'Admin\BookingController@getdetailBooking')->name('book.detail');
    Route::get('/booking/success/change/{id}/{status}', 'Admin\BookingController@getChangeBookingsuccess')->name('book.change');

    Route::get('getlogout', 'Admin\LoginController@getLogout')->name('admin.logout');
});



// Route::resource('admin/place', 'Admin\PlaceController');
// Route::resource('/tour', 'Admin\TourController');



//route frontend

Route::group(['middleware'=>'compressHTML'],function(){
    Route::get('/', 'Web\HomeController@getHome')->name('home.index');
    Route::get('/test', 'Web\HomeController@getTest');

    Route::get('/du-lich/{id}/{slug}.html', 'Web\HomeController@getCategoryParent');
    Route::get('/du-lich/tour-doanh-nghiep.html', 'Web\HomeController@getTourDoanhNghiep');
    Route::get('/du-lich-tai/{id}/{slug}.html', 'Web\HomeController@getCategoryChild');
    Route::get('/chi-tiet-tour/{id}-{slug}.html', 'Web\HomeController@getTourdetail');
    Route::post('/tim-kiem.html', 'Web\HomeController@getSearchTour')->name('seach.tour');
    Route::get('/ajax/loaitin/{id}', 'Web\HomeController@getFilterTour')->name('ajax.filter');
    Route::post('/loc-tour', 'Web\HomeController@getFilterTourHome')->name('filter.tour');

    //route booking
    Route::get('/dat-tour/{id}-{slug}.html', 'Web\BookController@getBooking');

    Route::get('/tin-tuc/{slug_detail}-news{id}.html', 'Web\NewsController@detail')->where([
        'slug_detail'=>'[^/]*',
        'id'=>'[^/]*'
    ]);
    Route::get('/tin-tuc/{slug}', 'Web\NewsController@index');
    Route::post('/dat-tour/{id}-{slug}.html', 'Web\BookController@postBooking1');

    Route::post('/dat-tour/user={id_user}&tong={total}/{id_book}/{id}-{slug}.html', 'Web\BookController@postBooking2');
    Route::get('/dat-tour/{id_user}/{id_tour}/{id_book}-bookview.html', 'Web\BookController@getviewBooking2')->name('bookview');

    Route::post('/confirm/{id_book}', 'Web\BookController@postConfirm1');
    Route::get('/confirm/thanhcong-{id_book}.html', 'Web\BookController@postConfirm2')->name('confirm2');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $table = 'category';

    protected $fillable = [
        'cat_name',
        'cat_rewrite',
        'cat_slug',
        'cat_type',
        'cat_active',
        'cat_parent_id',
        'cat_all_child',
    ];
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Arr;
use App\Models\Category;
use Validator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $category=Category::where('cat_parent_id',0)->paginate(20);
        return view('admin.pages.category.list',compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
       
        return view('admin.pages.category.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validate = Validator::make(
            $request->all(),
            [
                'cat_name' => 'required|unique:category|min:5|max:255'
            ],
        
            [
                'required' => ':attribute Không được để trống',
                'min' => ':attribute Không được nhỏ hơn :min',
                'max' => ':attribute Không được lớn hơn :max',
                'unique' => ':attribute Không được trùng lặp'
            ],
        
            [
                'cat_name' => 'Tiêu đề',
            ]
        
        );
        if ($validate->fails()) {
            return View('admin.pages.category.add')->withErrors($validate);
        }else{
            $cate = new Category;
            $cate->cat_name = $request->cat_name;
            $cate->cat_type = $request->cat_type;
            $cate->cat_rewrite = creatRewite($request->cat_name);
            $cate->cat_slug = Str::slug($request->cat_name,'-');
            $cate->cat_active = 1;
            $cate->cat_parent_id = 0;
    
            $cate->save();
    
            
            return redirect()->route('category.index')->with(['success'=>' Thêm mới danh mục thành công !']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $cat = Category::findOrFail($id);
        return view('admin.pages.category.edit',compact('cat'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $validate = Validator::make(
            $request->all(),
            [
                'cat_name' => 'required|min:5|max:255'
            ],
        
            [
                'required' => ':attribute Không được để trống',
                'min' => ':attribute Không được nhỏ hơn :min',
                'max' => ':attribute Không được lớn hơn :max',
                'unique' => ':attribute Không được trùng lặp'
            ],
        
            [
                'cat_name' => 'Tiêu đề',
            ]
        
        );
        if ($validate->fails()) {
            // dd('exit');
            $cat = Category::findOrFail($id);
            // $cate_child = Category::findOrFail($id);
            return View('admin.pages.category.edit',compact('cat'))->withErrors($validate);
            // return redirect()->back()
        }else{
            $cate = Category::findOrFail($id);
            $cate->cat_name = $request->cat_name;
            $cate->cat_type = $request->cat_type;
            $cate->cat_rewrite = creatRewite($request->cat_name);
            $cate->cat_slug = Str::slug($request->cat_name,'-');
            $cate->cat_active = 1;
            $cate->cat_parent_id = 0;
    
            $cate->save();
    
            
            return redirect()->route('category.index')->with(['success'=>' Cập nhật danh mục thành công !']);
        }
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function delete($id)
    {
        $cate = Category::findOrFail($id);
        $cate_parent_id = DB::table('category')->select()->where('cat_parent_id',$id)->get();
        $cate_parent_id = Arr::flatten($cate_parent_id);
        if(!empty($cate_parent_id)){
            return redirect()->back()->with(['error'=>' bạn không thể xóa khi danh mục cha có danh mục con !']);
        }else{
            $cate->delete();
            return redirect()->back()->with(['success'=>' Bạn đã xóa thành công !']);
        }
    }


    public function indexCateChild($id)
    {
        
        $cate =  DB::table('category')->select('id','cat_name')->where('id',$id)->get();
        $cate_child = category::where('cat_parent_id',$id)->paginate(20);
        // dd($cate_child->cat_place_id);
        $place = DB::table('place')->select('id','pla_name')->get();
        return view('admin.pages.category.categorychild.list',compact('cate','cate_child','place'));
    }
    public function createCateChild($id)
    {
        
        // $cate_last = DB::table('category')->get();
        // $cate_last = Arr::flatten($cate_last);
        // $last = end($cate_last);
        // dd($last->id);
       
        $cate = DB::table('category')->select('id','cat_name')->where('id',$id)->get();
        $cate = Arr::flatten($cate);
        $place = DB::table('place')->select('id','pla_name')->get();
        return view('admin.pages.category.categorychild.add',compact('cate','place'));
    }
    public function storeCateChild(Request $request,$id){
       
        $validate = Validator::make(
            $request->all(),
            [
                'cat_name' => 'required|unique:category|min:2|max:255'
            ],
            [
                'required' => ':attribute Không được để trống',
                'min' => ':attribute Không được nhỏ hơn :min',
                'max' => ':attribute Không được lớn hơn :max',
                'unique' => ':attribute Không được trùng lặp'
            ],
            [
                'cat_name' => 'Tiêu đề',
            ]
        
        );
        if ($validate->fails()){
            return redirect()->back()->withErrors($validate);
        }else{
            $cat_parent = Category::select('id','cat_name','cat_type','cat_all_child')->where('id',$id)->first();
          
            $cate = new Category;
            $cate->cat_name = $request->cat_name;
            $cate->cat_type = $cat_parent->cat_type;
            $cate->cat_rewrite = creatRewite($request->cat_name);
            $cate->cat_slug = Str::slug($request->cat_name,'-');
            $cate->cat_place_id = $request->cat_place_id;
            $cate->cat_active = 1;
            $cate->cat_parent_id = (int)$id;

            // dd($cate);
            if ($cate->save()){
                if ($cat_parent->cat_all_child==null){
                    $cat_all_child[] = $cate->id;
                    $cat_all_child = implode(',', $cat_all_child);
                }else{
                    $cat_all_child = explode(',', $cat_parent->cat_all_child);
                    $cat_all_child = array_filter($cat_all_child);
                    $cat_all_child[] = $cate->id;
                    $cat_all_child = implode(',', $cat_all_child);
                }

                $cat_parent->cat_all_child = $cat_all_child;
                $cat_parent->save();
                return redirect()->route('catechild.index',$id)->with(['success'=>' Thêm mới danh mục con thành công !']);
            }
            

        }
       
    }
    public function showCateChild($id){
        $cate_child = Category::findOrFail($id);
        $place = DB::table('place')->select('id','pla_name')->get();
        return view('admin.pages.category.categorychild.edit',compact('cate_child','place'));
    }
    public function editCateChild(Request $request,$id){

        $validate = Validator::make(
            $request->all(),
            [
                'cat_name' => 'required|min:2|max:255'
            ],
            [
                'required' => ':attribute Không được để trống',
                'min' => ':attribute Không được nhỏ hơn :min',
                'max' => ':attribute Không được lớn hơn :max',
                'unique' => ':attribute Không được trùng lặp'
            ],
            [
                'cat_name' => 'Tiêu đề',
            ]
        
        );

        if ($validate->fails()) {
            return redirect()->back()->withErrors($validate);
        }else{
            $cate = Category::findOrFail($id);
            $cat_parent = DB::table('category')->select('id','cat_name','cat_type')->where('id',$id)->first();
            $cate->cat_place_id = $request->cat_place_id;
            $cate->cat_name = $request->cat_name;
            $cate->cat_type = $cat_parent->cat_type;
            $cate->cat_rewrite = creatRewite($request->cat_name);
            $cate->cat_slug = Str::slug($request->cat_name,'-');
            $cate->cat_active = 1;
          
            $cate->save();


            $cate_parent_id = $cate->cat_parent_id;
    
            return redirect()->route('catechild.index',$cate_parent_id)->with(['success'=>' Cập nhật danh mục thành công !']);
        }
    }
    public function deleteCateChild($id){
        $cate = Category::findOrFail($id);

resources/views/admin/pages/category/add.blade.php
@php
    
// dd($errors->all());
@endphp

@extends('admin.layout.master')

@section('content') 
<section class="content-header">
    <div><ol class="breadcrumb">
            <li><a href="/admin/dashboard"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li><a href="{{route('category.index')}}">Danh sách danh mục</a></li>
            <li class="active">Thêm danh mục</li>
        </ol></div>
    <h1>
        Thêm danh mục mới
    </h1>
</section>
<section class="content">
    <!-- Info boxes -->
    <div class="row">
      <div class="col-md-4">
          @if(count($errors) > 0)
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
        @endif
      </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
            <form action="{{route('category.store')}}" role="form" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="box-body">
                  <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                            <label>Tên Danh mục</label>
                            <input type="text" name="cat_name" class="form-control" placeholder="Nhập tên danh mục">
                        </div>
                      </div>
                      <div class="col-md-4">
                          <div class="form-group">
                              <label>Loại Danh mục</label>
                              <div>
                                  <select name="cat_type" id="" style="width: 100%; height: 34px">
                                      <option value="0" selected> - Chọn loại danh mục</option>
                                      <option value="trongnuoc">Du lịch trong nước</option>
                                      <option value="doanhnghiep">Du lịch cho doanh nghiệp</option>
                                      <option value="nuocngoai">Du lịch nước ngoài</option>
                                      <option value="tintuc">Tin tức du lịch</option>
                                  </select>
                              </div>
                          </div>
                      </div>
                  </div>
                </div>
                <!-- /.box-body -->
  
                <div class="box-footer">
                  <button type="submit" class="btn btn-primary">Thêm mới</button>
                </div>
              </form>
            </div>
          </div>
    </div>
    <!-- /.row -->
</section>
@endsection

resources/views/admin/pages/category/edit.blade.php
@php
    
@endphp

@extends('admin.layout.master')

@section('content') 
<section class="content-header">
    <div><ol class="breadcrumb">
            <li><a href="/admin/dashboard"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li><a href="{{route('category.index')}}">Danh sách danh mục</a></li>
            <li class="active">Sửa danh mục</li>
        </ol></div>
    <h1>
        Sửa danh mục
    </h1>
</section>
<section class="content">
    <!-- Info boxes -->
    <div class="row">
        <div class="col-md-4">
            @if(count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
          @endif
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box box-warning">
              <!-- /.box-header -->
              <!-- form start -->
            <form action="{{asset('admin/category')}}/{{$cat->id}}/edit" role="form" method="GET" enctype="multipart/form-data">
                @csrf
                <div class="box-body">
                  <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                            <label>Nhập tên danh mục mới *</label>
                        <input type="text" name="cat_name" value="{{$cat->cat_name}}" class="form-control" placeholder="Nhập tên danh mục">
                        </div>
                      </div>
                      <div class="col-md-4">
                          <div class="form-group">
                              <label>Loại Danh mục</label>
                              <div>
                                  <select name="cat_type" id="" style="width: 100%; height: 34px">
                                        <option value="0" selected> - Chọn loại danh mục</option>
                                        <option value="trongnuoc">Du lịch trong nước</option>
                                        <option value="doanhnghiep">Du lịch cho doanh nghiệp</option>
                                        <option value="nuocngoai">Du lịch nước ngoài</option>
                                        <option value="tintuc">Tin tức du lịch</option>
                                  </select>
                              </div>
                          </div>
                      </div>
                  </div>
                </div>
                <!-- /.box-body -->
  
                <div class="box-footer">
                  <button type="submit" class="btn btn-primary">Cập nhật</button>
                </div>
              </form>
            </div>
          </div>
    </div>
    <!-- /.row -->
</section>
@endsection

@section('script')




@endsection

@section('style')

<style>
    
</style>
    
@endsection

resources/views/admin/pages/category/list.blade.php
@php 

@endphp

@extends('admin.layout.master')

@section('content') 
    <section class="content-header">
        <div>
            <ol class="breadcrumb">
                <li><a href="/admin/dashboard"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li class="active">Danh sách danh mục</li>
            </ol>
        </div>
    </section>
    <section class="content">
      <div class="row">
        <div class="col-md-12">
            @if (session('success'))
              <div class="alert alert-success">
                    <strong>{{ session('success') }}</strong>
              </div>
            @elseif(session('error'))
            <div class="alert alert-danger">
              <strong>{{ session('error') }}</strong>
            </div>
            @endif
        </div>
      </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header with-border">
                      <h3 class="box-title">Danh sách danh mục</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                      <table class="table table-bordered">
                        <tbody><tr>
                          <th style="width: 10px">STT</th>
                          <th>Danh mục</th>
                            <th>Loại danh mục</th>
                          <th style="width: 300px">Hành động</th>
                        </tr>
                        @php $stt = 1; @endphp
                        @foreach ($category as $cat)
                        <tr>
                        <td>{{$stt++}}</td>
                        <td style="text-transform: uppercase;">{{$cat->cat_name}}</td>
                            <td style="width: 100px">{{$cat->cat_type}}</td>
                          <td>
                            <a class="btn btn-success" href="{{asset('admin/child/category/')}}/{{$cat->id}}"><i class="fa fa-fw fa-list-ul"></i> Danh mục con</a>
                            <a class="btn btn-warning" href="{{asset('admin/category')}}/{{$cat->id}}"><i class="fa fa-edit"></i> Sửa</a>
                            <a class="btn btn-danger hidden"  data-toggle="modal" data-target="#modal-default-{{$cat->id}}"><i class="fa fa-trash"></i> Xoá</a>
                          </td>
                        </tr>

                        <div class="modal fade" id="modal-default-{{$cat->id}}" style="display: none;">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">×</span></button>
                                <h4 class="modal-title">Bạn có chắn chắn muốn xóa {{$cat->cat_name}} ?</h4>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Hủy bỏ</button>
                                <a href="{{asset('admin/delete')}}/{{$cat->id}}" class="btn btn-danger">Xóa bỏ</a>
                              </div>
                            </div>
                          </div>
                        </div>
                        @endforeach
                      </tbody></table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                    <a class="btn btn-primary" href="{{route('category.create')}}">Thêm</a>
                      <div class="paginate_cate text-center">
                        {{$category->links()}}
                      </div>
                    </div>
                  </div>
            </div>
        </div>
    </section>
@endsection