routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('foo', function () {
    return 'Hello World';
});

Route::group(['prefix'=>'admin/login','middleware'=>'CheckLogin'],function(){
    Route::get('/', 'Admin\LoginController@getLogin')->name('admin.login');
    Route::post('/', 'Admin\LoginController@postLogin')->name('admin.post.login');
});

Route::group(['prefix'=>'admin','middleware'=>'CheckAdmin'],function(){
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::resource('place', 'Admin\PlaceController');
    // Route tour
    Route::resource('tour', 'Admin\TourController');

    Route::post('/tour/update/{id}','Admin\TourController@updateTour');
    Route::get('/tour/delete/{id}','Admin\TourController@deleteTour');
    
    Route::resource('news', 'Admin\NewsController');

    // Route danh mục cha
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('banner', 'Admin\BannerController');
    Route::get('/delete/{id}','Admin\CategoryController@delete');
    // Route danh mục con
    Route::get('/child/category/{id}','Admin\CategoryController@indexCateChild')->name('catechild.index');
    Route::get('/child/category/add/{id}','Admin\CategoryController@createCateChild');
    Route::post('/child/category/add/{id}','Admin\CategoryController@storeCateChild');
    Route::get('/child/category/edit/{id}','Admin\CategoryController@showCateChild');
    Route::post('/child/category/edit/{id}','Admin\CategoryController@editCateChild');
    Route::get('/child/category/delete/{id}','Admin\CategoryController@deleteCateChild');

    //route quan ly dat hang
    Route::get('/booking', 'Admin\BookingController@getBooking')->name('book.index');
    Route::get('/booking/success', 'Admin\BookingController@getBookingSuccess')->name('book.success');
    Route::get('/booking/{id}', 'Admin\BookingController@getdetailBooking')->name('book.detail');
    Route::get('/booking/success/change/{id}/{status}', 'Admin\BookingController@getChangeBookingsuccess')->name('book.change');

    Route::get('getlogout', 'Admin\LoginController@getLogout')->name('admin.logout');
});



// Route::resource('admin/place', 'Admin\PlaceController');
// Route::resource('/tour', 'Admin\TourController');



//route frontend

Route::group(['middleware'=>'compressHTML'],function(){
    Route::get('/', 'Web\HomeController@getHome')->name('home.index');
    Route::get('/test', 'Web\HomeController@getTest');

    Route::get('/du-lich/{id}/{slug}.html', 'Web\HomeController@getCategoryParent');
    Route::get('/du-lich/tour-doanh-nghiep.html', 'Web\HomeController@getTourDoanhNghiep');
    Route::get('/du-lich-tai/{id}/{slug}.html', 'Web\HomeController@getCategoryChild');
    Route::get('/chi-tiet-tour/{id}-{slug}.html', 'Web\HomeController@getTourdetail');
    Route::post('/tim-kiem.html', 'Web\HomeController@getSearchTour')->name('seach.tour');
    Route::get('/ajax/loaitin/{id}', 'Web\HomeController@getFilterTour')->name('ajax.filter');
    Route::post('/loc-tour', 'Web\HomeController@getFilterTourHome')->name('filter.tour');

    //route booking
    Route::get('/dat-tour/{id}-{slug}.html', 'Web\BookController@getBooking');

    Route::get('/tin-tuc/{slug_detail}-news{id}.html', 'Web\NewsController@detail')->where([
        'slug_detail'=>'[^/]*',
        'id'=>'[^/]*'
    ]);
    Route::get('/tin-tuc/{slug}', 'Web\NewsController@index');
    Route::post('/dat-tour/{id}-{slug}.html', 'Web\BookController@postBooking1');

    Route::post('/dat-tour/user={id_user}&tong={total}/{id_book}/{id}-{slug}.html', 'Web\BookController@postBooking2');
    Route::get('/dat-tour/{id_user}/{id_tour}/{id_book}-bookview.html', 'Web\BookController@getviewBooking2')->name('bookview');

    Route::post('/confirm/{id_book}', 'Web\BookController@postConfirm1');
    Route::get('/confirm/thanhcong-{id_book}.html', 'Web\BookController@postConfirm2')->name('confirm2');
});

app/Models/Place.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Place extends Model
{
    //
    protected $table = 'place';

    protected $fillable = [
        'pla_code',
        'pla_name',
        'pla_description',
        'pla_picture',
        'pla_slide'
    ];
}

app/Http/Controllers/Admin/PlaceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Place;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Validator;

class PlaceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $places_tn = Place::where('pla_active',1)->where('pla_type',1)->get();
        $places_nn = Place::where('pla_active',1)->where('pla_type',0)->get();

        return view('admin.pages.place.list',compact('places_tn','places_nn'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.pages.place.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator::make($request->all(),
            [
                'pla_name' => 'required|min:2|max:255|unique:place',
                'pla_description' => 'required',
            ],
            [
                'pla_name.required' => 'Tên địa chỉ không được để trống.',
                'pla_name.min' => 'Tên địa chỉ quá ngắn, mời bạn nhập lại!',
                'pla_name.max' => 'Tên địa chỉ quá dài, mời bạn nhập lại!',
                'pla_name.unique' => 'Tên địa chỉ không được trùng.',
                'pla_description.required' => 'Mô tả không được để trống.',
            ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        $places = new Place();
        $places->pla_name = $request->input('pla_name');
        $places->pla_code = $request->input('pla_code');
        $places->pla_type = $request->input('pla_type');
        $places->pla_active = 1;
        $places->pla_slug = Str::slug($request->input('pla_name'));
        $places->pla_description = $request->input('pla_description');

        if ($request->hasFile('pla_photo')) {
            $picture = $request->file('pla_photo');
            $name = 'Img-'.time().'.'.$picture->getClientOriginalExtension();
            $destinationPath = public_path('/uploadfile/places');
            $picture->move($destinationPath, $name);
            $places->pla_picture = $name;
        }
        $notification = array(
            'message' => 'Save product successfully!',
            'alert-type' => 'success'
        );
        if ($places->save()){
            return redirect('admin/place')->with($notification);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        dd(1+$id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $place = Place::findOrFail($id);
        return view('admin.pages.place.edit',compact('place'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $place = Place::FindOrFail($id);
        $validator = Validator::make($request->all(),
            [
                'pla_name' => 'required|min:2|max:255',
                'pla_description' => 'required',
            ],
            [
                'pla_name.required' => 'Tên địa chỉ không được để trống.',
                'pla_name.min' => 'Tên địa chỉ quá ngắn, mời bạn nhập lại!',
                'pla_name.max' => 'Tên địa chỉ quá dài, mời bạn nhập lại!',
                'pla_description.required' => 'Mô tả không được để trống.',
            ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        $place->pla_name = $request->input('pla_name');
        $place->pla_code = $request->input('pla_code');
        $place->pla_type = $request->input('pla_type');
        $place->pla_active = 1;
        $place->pla_slug = Str::slug($request->input('pla_name'));
        $place->pla_description = $request->input('pla_description');

        if ($request->hasFile('pla_photo')) {
            $picture = $request->file('pla_photo');
            $name = 'Img-'.time().'.'.$picture->getClientOriginalExtension();
            $destinationPath = public_path('/uploadfile/places');
            $picture->move($destinationPath, $name);
            $place->pla_picture = $name;
        }
        $notification = array(
            'message' => 'Save product successfully!',
            'alert-type' => 'success'
        );
        if ($place->save()){
            return redirect('admin/place')->with($notification);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/pages/place/add.blade.php
@extends('admin.layout.master')

@section('content')
    <section class="content-header">
        <div><ol class="breadcrumb">
                <li><a href="/admin/dashboard"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li><a href="{{route('place.index')}}">Danh sách địa điểm</a></li>
                <li class="active">Thêm địa điểm du lịch</li>
            </ol></div>
        <h1>
            Thêm địa điểm du lịch
        </h1>
    </section>
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" enctype="multipart/form-data" action="{{asset('admin/place')}}" method="POST">
                        @csrf
                        <div class="box-body">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input type="text" class="form-control" name="pla_name" id="" placeholder="Enter place name">
                                </div>
                                <div class="form-group">
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="pla_type" id="optionsRadios1" value="1" checked="">
                                            Trong nước
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="pla_type" id="optionsRadios2" value="0">
                                            Nước ngoài
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Zip Code</label>
                                    <input type="text" class="form-control" name="pla_code" id="" placeholder="Enter zip code">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12" style="padding: 10px 30px;">
                                    <label>Mô tả tổng quan *</label>
                                    <textarea name="pla_description"></textarea>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="exampleInputFile">Photo</label>
                                <input type="file" name="pla_photo" id="" multiple="multiple">
                            </div>
                        </div>
                        <div class="box-footer" style="margin-left: 20px">
                            <button type="submit" class="btn btn-primary">Thêm</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
    </section>
@endsection
@section('script')

    <script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>


    <script>
        CKEDITOR.replace( 'pla_description' );
    </script>

@endsection

resources/views/admin/pages/place/edit.blade.php
@extends('admin.layout.master')

@section('content')
    <section class="content-header">
        <div><ol class="breadcrumb">
                <li><a href="/admin/dashboard"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li><a href="{{route('place.index')}}">Danh sách địa điểm</a></li>
                <li class="active">Place</li>
            </ol></div>
        <h1>
            Sửa địa điểm du lịch
        </h1>
    </section>
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-warning">
                    <form role="form" enctype="multipart/form-data" action="{{asset('admin/place/').'/'.$place->id}}" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="box-body">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input type="text" class="form-control" name="pla_name" value="{{$place->pla_name}}" id="" placeholder="Enter place name">
                                </div>
                                <div class="form-group">
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="pla_type" id="optionsRadios1" value="1" checked="">
                                            Trong nước
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="pla_type" id="optionsRadios2" value="0">
                                            Nước ngoài
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Zip Code</label>
                                    <input type="text" class="form-control" name="pla_code" value="{{$place->pla_code}}" id="" placeholder="Enter zip code">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12" style="padding: 10px 30px;">
                                    <label>Mô tả tổng quan *</label>
                                    <textarea name="pla_description">{!! $place->pla_description !!}</textarea>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="exampleInputFile">Photo</label>
                                <input type="file" name="pla_photo" id="" multiple="multiple">

                                <div class="img_old">
                                    <img src="{{asset('uploadfile/places/').'/'.$place->pla_picture}}" width="200px" height="200px" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="box-footer" style="margin-left: 20px">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
    </section>
@endsection
@section('script')

    <script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>


    <script>
        CKEDITOR.replace( 'pla_description' );
    </script>

@endsection

resources/views/admin/pages/place/list.blade.php
@extends('admin.layout.master')

@section('content')
    <section class="content-header">
        <div>
            <ol class="breadcrumb">
                <li><a href="/admin/dashboard"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li class="active">Danh sách địa điểm</li>
            </ol>
        </div>
        <h1>
            Danh sách địa điểm du lịch
        </h1>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="mt-3">
                    <ul class="nav nav-tabs">
                      <li class="nav-item active">
                        <a class="nav-link active" data-toggle="tab" href="#trongnuoc">Trong nước</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#nuocngoai">Nước ngoài</a>
                      </li>
                    </ul>
                    <div class="tab-content">
                      <div id="trongnuoc" class="tab-pane active">
                        <div class="box box-primary">
                            <div class="box-body table-responsive no-padding">
                                <table class="table table-hover">
                                    <tbody>
                                        <tr>
                                            <th>STT</th>
                                            <th>Picture</th>
                                            <th>Place Name</th>
                                            <th>Ngày tạo</th>
                                            <th>Mô tả</th>
                                            <th>Địa điểm</th>
                                            <th>Trạng thái</th>
                                            <th>Hành động</th>
                                        </tr>
                                        @foreach($places_tn as $key=>$pla)
                                            <tr>
                                                <td style="text-align: center">{{$key+1}}</td>
                                                @if(isset($pla->pla_picture))
                                                    <td>
                                                        <div class="img_pla" style="width: 100px;">
                                                            <img src="{{asset('uploadfile/places/').'/'.$pla->pla_picture}}" width="100%" height="100%" alt="">
                                                        </div>
                                                    </td>
                                                @else
                                                    <td><img src="" alt=""></td>
                                                @endif
                                                <td>{{$pla->pla_name}}</td>
                                                <td>{{$pla->created_at}}</td>
                                                <td><div class="content_place">{!! $pla->pla_description !!}</div></td>
                                                <td>{{$pla->pla_type==1?'trong nước':'nước ngoài'}}</td>
                                                @if($pla->pla_active===1)
                                                    <td><span class="label label-success">Hiển thị</span></td>
                                                @else
                                                    <td><span class="label label-danger">Đã ẩn</span></td>
                                                @endif
                                                <td>
                                                    <a class="btn btn-warning" href="{{'/admin/place/'.$pla->id.'/edit'}}"><i class="fa fa-edit"></i> Sửa</a>
                                                    <a class="btn btn-danger hidden" href="#"><i class="fa fa-trash"></i> Xoá</a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <a class="btn btn-primary" href="/admin/place/create">Thêm</a>
                            </div>
                        </div>
                      </div>
                      <div id="nuocngoai" class="tab-pane fade">
                        <div class="box box-primary">
                            <div class="box-body table-responsive no-padding">
                                <table class="table table-hover">
                                    <tbody>
                                        <tr>
                                            <th>STT</th>
                                            <th>Picture</th>
                                            <th>Place Name</th>
                                            <th>Ngày tạo</th>
                                            <th>Mô tả</th>
                                            <th>Địa điểm</th>
                                            <th>Trạng thái</th>
                                            <th>Hành động</th>
                                        </tr>
                                        @foreach($places_nn as $key=>$pla)
                                            <tr>
                                                <td style="text-align: center">{{$key+1}}</td>
                                                @if(isset($pla->pla_picture))
                                                    <td>
                                                        <div class="img_pla" style="width: 100px;">
                                                            <img src="{{asset('uploadfile/places/').'/'.$pla->pla_picture}}" width="100%" height="100%" alt="">
                                                        </div>
                                                    </td>
                                                @else
                                                    <td><img src="" alt=""></td>
                                                @endif
                                                <td>{{$pla->pla_name}}</td>
                                                <td>{{$pla->created_at}}</td>
                                                <td><div class="content_place">{!! $pla->pla_description !!}</div></td>
                                                <td>{{$pla->pla_type==1?'trong nước':'nước ngoài'}}</td>
                                                @if($pla->pla_active===1)
                                                    <td><span class="label label-success">Hiển thị</span></td>
                                                @else
                                                    <td><span class="label label-danger">Đã ẩn</span></td>
                                                @endif
                                                <td>
                                                    <a class="btn btn-warning" href="{{'/admin/place/'.$pla->id.'/edit'}}"><i class="fa fa-edit"></i> Sửa</a>
                                                    <a class="btn btn-danger hidden" href="#"><i class="fa fa-trash"></i> Xoá</a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <a class="btn btn-primary" href="/admin/place/create">Thêm</a>
                            </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  
            </div>
        </div>
    </section>
@endsection