routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('foo', function () {
    return 'Hello World';
});

Route::group(['prefix'=>'admin/login','middleware'=>'CheckLogin'],function(){
    Route::get('/', 'Admin\LoginController@getLogin')->name('admin.login');
    Route::post('/', 'Admin\LoginController@postLogin')->name('admin.post.login');
});

Route::group(['prefix'=>'admin','middleware'=>'CheckAdmin'],function(){
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::resource('place', 'Admin\PlaceController');
    // Route tour
    Route::resource('tour', 'Admin\TourController');

    Route::post('/tour/update/{id}','Admin\TourController@updateTour');
    Route::get('/tour/delete/{id}','Admin\TourController@deleteTour');
    
    Route::resource('news', 'Admin\NewsController');

    // Route danh mục cha
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('banner', 'Admin\BannerController');
    Route::get('/delete/{id}','Admin\CategoryController@delete');
    // Route danh mục con
    Route::get('/child/category/{id}','Admin\CategoryController@indexCateChild')->name('catechild.index');
    Route::get('/child/category/add/{id}','Admin\CategoryController@createCateChild');
    Route::post('/child/category/add/{id}','Admin\CategoryController@storeCateChild');
    Route::get('/child/category/edit/{id}','Admin\CategoryController@showCateChild');
    Route::post('/child/category/edit/{id}','Admin\CategoryController@editCateChild');
    Route::get('/child/category/delete/{id}','Admin\CategoryController@deleteCateChild');

    //route quan ly dat hang
    Route::get('/booking', 'Admin\BookingController@getBooking')->name('book.index');
    Route::get('/booking/success', 'Admin\BookingController@getBookingSuccess')->name('book.success');
    Route::get('/booking/{id}', 'Admin\BookingController@getdetailBooking')->name('book.detail');
    Route::get('/booking/success/change/{id}/{status}', 'Admin\BookingController@getChangeBookingsuccess')->name('book.change');

    Route::get('getlogout', 'Admin\LoginController@getLogout')->name('admin.logout');
});



// Route::resource('admin/place', 'Admin\PlaceController');
// Route::resource('/tour', 'Admin\TourController');



//route frontend

Route::group(['middleware'=>'compressHTML'],function(){
    Route::get('/', 'Web\HomeController@getHome')->name('home.index');
    Route::get('/test', 'Web\HomeController@getTest');

    Route::get('/du-lich/{id}/{slug}.html', 'Web\HomeController@getCategoryParent');
    Route::get('/du-lich/tour-doanh-nghiep.html', 'Web\HomeController@getTourDoanhNghiep');
    Route::get('/du-lich-tai/{id}/{slug}.html', 'Web\HomeController@getCategoryChild');
    Route::get('/chi-tiet-tour/{id}-{slug}.html', 'Web\HomeController@getTourdetail');
    Route::post('/tim-kiem.html', 'Web\HomeController@getSearchTour')->name('seach.tour');
    Route::get('/ajax/loaitin/{id}', 'Web\HomeController@getFilterTour')->name('ajax.filter');
    Route::post('/loc-tour', 'Web\HomeController@getFilterTourHome')->name('filter.tour');

    //route booking
    Route::get('/dat-tour/{id}-{slug}.html', 'Web\BookController@getBooking');

    Route::get('/tin-tuc/{slug_detail}-news{id}.html', 'Web\NewsController@detail')->where([
        'slug_detail'=>'[^/]*',
        'id'=>'[^/]*'
    ]);
    Route::get('/tin-tuc/{slug}', 'Web\NewsController@index');
    Route::post('/dat-tour/{id}-{slug}.html', 'Web\BookController@postBooking1');

    Route::post('/dat-tour/user={id_user}&tong={total}/{id_book}/{id}-{slug}.html', 'Web\BookController@postBooking2');
    Route::get('/dat-tour/{id_user}/{id_tour}/{id_book}-bookview.html', 'Web\BookController@getviewBooking2')->name('bookview');

    Route::post('/confirm/{id_book}', 'Web\BookController@postConfirm1');
    Route::get('/confirm/thanhcong-{id_book}.html', 'Web\BookController@postConfirm2')->name('confirm2');
});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    //
    protected $table = 'news';

    protected $fillable = [
        'new_cat_id',
        'new_user_id',
        'new_title',
        'new_teaser',
        'new_description',
        'new_picture'
    ];
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\News;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use PHPUnit\Framework\StaticAnalysis\HappyPath\AssertNotInstanceOf\A;
use Validator;


class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $news = News::where('new_active',1)->paginate(30);
        $user=Auth::user();
        $categories = Category::where('cat_active',1)->where('cat_type','tintuc')->get();
        return view('admin.pages.news.list',compact('news','user','categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::where('cat_active',1)->where('cat_type','tintuc')->get();
        $cat_news_child = null;
        $cat_parent = $categories->groupBy('cat_parent_id');
        if (!empty($cat_parent[0])){
            foreach ($cat_parent[0] as $key=>$cat_item) {
                $arr_cat_child_id = explode(',', $cat_item->cat_all_child);
                $cat_news_child = Category::whereIn('id', $arr_cat_child_id)->where('cat_active', 1)->where('cat_type','tintuc')->get();
            }
        }

        return view('admin.pages.news.add',compact('cat_news_child'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator::make($request->all(),
            [
                'new_title' => 'required|min:3|max:255|unique:news',
                'new_cat_id' => 'required|numeric',
                'new_description' => 'required|unique:news',
            ],
            [
                'new_title.required' => 'Tin không được để trống.',
                'new_title.min' => 'Tin quá ngắn, mời bạn nhập lại!',
                'new_title.max' => 'Tên tin quá dài, mời bạn nhập lại!',
                'new_title.unique' => 'Tên tin không được trùng.',
                'new_cat_id.required' => 'Mời chọn danh sách tin tức.',
                'new_description.required' => 'Mô tả không được để trống.',
                'new_description.unique' => 'Tên tin không được giống nhau.',
            ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        $news = new News();
        $news->new_title = $request->input('new_title');
        $news->new_cat_id = $request->input('new_cat_id');
        $news->new_user_id  = Auth::user()->id;
        $news->new_active = 1;
        $news->new_slug = Str::slug($request->input('new_title'));
        $news->new_description = $request->input('new_description');
        $news->new_teaser = Str::limit(strip_tags(html_entity_decode($request->input('new_description'))),300,'...');

        if ($request->hasFile('new_picture')) {
            $picture = $request->file('new_picture');
            $name = 'Img-news-'.time().'.'.$picture->getClientOriginalExtension();
            $destinationPath = public_path('/uploadfile/news');
            $picture->move($destinationPath, $name);
            $news->new_picture = $name;
        }
        $notification = array(
            'message' => 'Save news successfully!',
            'alert-type' => 'success'
        );
        if ($news->save()){
            return redirect('admin/news')->with($notification);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $news = News::findOrFail($id);
        $categories = Category::where('cat_active',1)->where('cat_type','tintuc')->get();
        $cat_news_child = null;
        $cat_parent = $categories->groupBy('cat_parent_id');
        if (!empty($cat_parent[0])){
            foreach ($cat_parent[0] as $key=>$cat_item) {
                $arr_cat_child_id = explode(',', $cat_item->cat_all_child);
                $cat_news_child = Category::whereIn('id', $arr_cat_child_id)->where('cat_active', 1)->where('cat_type','tintuc')->get();
            }
        }
        return view('admin.pages.news.edit',compact('news','cat_news_child'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $news = News::FindOrFail($id);
        $validator = Validator::make($request->all(),
            [
                'new_title' => 'required|min:3|max:255',
                'new_cat_id' => 'required|numeric',
                'new_description' => 'required',
            ],
            [
                'new_title.required' => 'Tin không được để trống.',
                'new_title.min' => 'Tin quá ngắn, mời bạn nhập lại!',
                'new_title.max' => 'Tên tin quá dài, mời bạn nhập lại!',
                'new_cat_id.required' => 'Mời chọn danh sách tin tức.',
                'new_description.required' => 'Mô tả không được để trống.',
            ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        $news->new_title = $request->input('new_title');
        $news->new_cat_id = $request->input('new_cat_id');
        $news->new_user_id  = Auth::user()->id;
        $news->new_active = 1;
        $news->new_slug = Str::slug($request->input('new_title'));
        $news->new_description = $request->input('new_description');
        $news->new_teaser = Str::limit(strip_tags(html_entity_decode($request->input('new_description'))),300,'...');

        if ($request->hasFile('new_picture')) {
            $picture = $request->file('new_picture');
            $name = 'Img-news-'.time().'.'.$picture->getClientOriginalExtension();
            $destinationPath = public_path('/uploadfile/news');
            $picture->move($destinationPath, $name);
            $news->new_picture = $name;
        }
        $notification = array(
            'message' => 'Save news successfully!',
            'alert-type' => 'success'
        );
        if ($news->save()){
            return redirect('admin/news')->with($notification);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Web/NewsController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\News;
use Illuminate\Http\Request;

class NewsController extends Controller
{
    //
    public function index($slug){
        $category = Category::Where('cat_slug',$slug)->first();
        $news = News::Where('new_active',1)->where('new_cat_id',$category->id)->orderBy('id','desc')->paginate(6);
        $news_latest_relate =  null;
        $news_new  = null;
        $is_check_classified = count($news->toArray()['data']);
        if ($is_check_classified== 0 ){
            $news = null;
        }
        else
        {
            $news_latest_relate = News::Where('new_active',1)->where('new_cat_id',$category->id)->orderBy('id','desc')->limit(3)->get();
            $news_new = $news->first();
        }

        return view('web.pages.news.list_news',compact('news','news_new','news_latest_relate','category'));
    }
    public function detail($slug,$id){
        $news  =  News::findOrFail($id);
        $category = Category::Where('id',$news->new_cat_id)->first();
        return view('web.pages.news.detail_news',compact('news','category'));
    }
}

resources/views/admin/pages/news/add.blade.php
@extends('admin.layout.master')

@section('content')
    <section class="content-header">
        <div><ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li class="active">News</li>
            </ol></div>
        <h1>
            News
            <small>Add</small>
        </h1>
    </section>
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Quick Add</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" enctype="multipart/form-data" action="{{asset('admin/news')}}" method="POST">
                        @csrf
                        <div class="box-body">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">News Title</label>
                                    <input type="text" class="form-control" name="new_title" id="" placeholder="Enter news title">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Danh sách tin tức</label>
                                    <select name="new_cat_id" id="" style="width: 100%; height: 34px">
                                        @foreach($cat_news_child as $cat)
                                            <option value="{{$cat->id}}">{{$cat->cat_name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12" style="padding: 10px 30px;">
                                    <label>Mô tả tổng quan *</label>
                                    <textarea name="new_description"></textarea>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="exampleInputFile">Photo</label>
                                <input type="file" name="new_picture" id="" multiple="multiple">
                            </div>
                        </div>
                        <div class="box-footer" style="margin-left: 20px">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
    </section>
@endsection
@section('script')

    <script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>


    <script>
        var editor = CKEDITOR.replace( 'new_description',{
            disallowedContent:'a[!href];p(tip)'
        });

        editor.on( 'instanceReady', function() {
            console.log( editor.filter.allowedContent );
        } );

    </script>

@endsection

resources/views/admin/pages/news/edit.blade.php
@extends('admin.layout.master')

@section('content')
    <section class="content-header">
        <div><ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li class="active">News</li>
            </ol></div>
        <h1>
            News
            <small>Edit</small>
        </h1>
    </section>
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Quick Edit</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" enctype="multipart/form-data" action="{{asset('admin/news').'/'.$news->id}}" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="box-body">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">News Title</label>
                                    <input type="text" class="form-control" name="new_title" id="" value="{{$news->new_title}}" placeholder="Enter news title">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Danh sách tin tức</label>
                                    <select name="new_cat_id" id="" style="width: 100%; height: 34px">
                                        @foreach($cat_news_child as $cat)
                                            @if($cat->id==$news->new_cat_id)
                                                <option value="{{$cat->id}}" selected>{{$cat->cat_name}}</option>
                                            @else
                                                <option value="{{$cat->id}}">{{$cat->cat_name}}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12" style="padding: 10px 30px;">
                                    <label>Mô tả tổng quan *</label>
                                    <textarea name="new_description">{!! $news->new_description !!}</textarea>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="exampleInputFile">Photo</label>
                                <input type="file" name="new_picture" id="" multiple="multiple">

                                <div class="img_old">
                                    <img src="{{asset('uploadfile/news/').'/'.$news->new_picture}}" width="200px" height="200px" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="box-footer" style="margin-left: 20px">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
    </section>
@endsection
@section('script')

    <script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>


    <script>
        var editor = CKEDITOR.replace( 'new_description',{
            disallowedContent:'a[!href];p(tip)'
        });

        editor.on( 'instanceReady', function() {
            console.log( editor.filter.allowedContent );
        } );

    </script>

@endsection

resources/views/admin/pages/news/list.blade.php
@extends('admin.layout.master')

@section('content')
    <section class="content-header">
        <div>
            <ol class="breadcrumb">
                <li><a href="/dashboard"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li>Quản lý tin tức du lịch</li>
                <li class="active">Danh sách các tin tức</li>
            </ol>
        </div>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-2">
                @if (session('success'))
                    <div class="alert alert-success">
                        <strong>{{ session('success') }}</strong>
                    </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Danh sách tất cả các tin</h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <tbody>
                            <tr>
                                <th>STT</th>
                                <th>Hình ảnh</th>
                                <th>Tiêu đề</th>
                                <th>Người đăng tin</th>
                                <th>Danh mục tin tức</th>
                                <th>Ngày đăng</th>
                                <th>Trạng thái</th>
                                <th>Action</th>
                            </tr>
                            <tr>
                                @foreach($news as $key=>$item_news)
                                    <td>{{$key+1}}</td>
                                    @if(isset($item_news->new_picture))
                                        <td>
                                            <div class="img_pla" style="width: 100px;">
                                                <img src="{{asset('uploadfile/news/').'/'.$item_news->new_picture}}" width="100%" height="100%" alt="">
                                            </div>
                                        </td>
                                    @else
                                        <td><div class="img_pla" style="width: 100px;"><img src="{{asset('web/images/default.jpg')}}" width="100%" height="100%" alt=""></div></td>
                                    @endif
                                    <td style="width:300px">{{$item_news->new_title}}</td>
                                    <td>{{$user->name}}</td>
                                    @foreach($categories as $cat)
                                        @if($cat->id === $item_news->new_cat_id)
                                            <td>{{$cat->cat_name}}</td>
                                        @endif
                                    @endforeach
                                    <td>
                                        <div class="create_at">{{ $item_news->created_at }}</div>
                                    </td>
                                    @if($item_news->new_active===1)
                                        <td><span class="label label-success">Active</span></td>
                                    @else
                                        <td><span class="label label-danger">No Active</span></td>
                                    @endif
                                    <td>
                                        <a class="btn btn-success" data-toggle="modal" data-target="#modal-info-{{$item_news->id}}" title="chi tiết"><i class="fa fa-fw fa-info"></i></a>
                                        <a class="btn btn-warning" href="{{route('news.edit',[$item_news->id])}}"><i class="fa fa-edit"></i> Sửa</a>
                                        <a class="btn btn-danger" href="{{route('news.destroy',[$item_news->id])}}"><i class="fa fa-trash"></i>Xoá</a>
                                    </td>
                                </tr>
                                <div class="modal fade in" id="modal-info-{{$item_news->id}}" style="display: none;">
                                    <div class="modal-dialog modal_info">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">×</span></button>
                                                <h4 class="modal-title" style="font-weight: bold">{{$item_news->new_title}}</h4>
                                            </div>
                                            <div class="modal-body">
                                                <div class="content_info">
                                                    <div class="header_body header_news">
                                                        <div class="img_news">
                                                            <img src="{{asset('uploadfile/news'.'/'.$item_news->new_picture)}}" alt="Ảnh" width="250" height="230">
                                                        </div>
                                                    </div>
                                                    <div class="content_news">
                                                        <div class="info_news">
                                                            <p class="price">Người đăng : <b>{{$user->name}}</b></p>
                                                            <p>Ngày đăng tin : <b>{{ $item_news->created_at }}</b></p>
                                                            @foreach($categories as $cat)
                                                                @if($cat->id === $item_news->new_cat_id)
                                                                    <p class="price">Danh mục tin tức : <b>{{$cat->cat_name}}</b></p>
                                                                @endif
                                                            @endforeach
                                                            @if($item_news->new_active===1)
                                                                <p>Trạng thái : <b><span class="label label-success">Active</span></b></p>
                                                            @else
                                                                <p>Trạng thái : <b><span class="label label-danger">No Active</span></b></p>
                                                            @endif
                                                        </div>
                                                        <div class="description_news">
                                                            {!! $item_news->new_description !!}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a class="btn btn-primary" href="{{route('news.create')}}">Thêm</a>
                        <div class="paginate_cate text-center">
                            {{$news->links()}}
                        </div>
                    </div>
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
@endsection
@section('style')

    <style>
        .content_info{
            display: grid;
            grid-template-columns: 200px 1fr;
            grid-gap: 10px;
        }
        .header_news{
            width: 100%;
            display: inline-block !important;
        }
        .info_news{
            display: grid;
            grid-template-columns: 1fr 1fr;
            padding-bottom: 20px;
            border-bottom: 1px solid #777777c7;
        }
        .img_news{
            margin-bottom: 20px;
            border:1px solid #777777c7;
        }
        .img_news img{
            width: 100%;
            height: 200px;
        }
        .description_news{
            margin-top: 20px;
        }
    </style>

@endsection